theme = "frugalinnovation"
title = "Frugal Innovation"
	
[[menu.main]]
    name = "Fallstudien"
    url = "#"
    weight = 1
    identifier = "dropdown"
	
[[menu.main]]
    name = "Afrika"
    url = "/fallstudien/afrika/"
    weight = 1
    parent = "dropdown"   

[[menu.main]]
    name = "Asien"
    url = "/fallstudien/asien/"
    weight = 2
    parent = "dropdown" 

[[menu.main]]
    name = "Europa"
    url = "/fallstudien/europa/"
    weight = 4
    parent = "dropdown" 

[[menu.main]]
    name = "Nordamerika"
    url = "/fallstudien/nordamerika/"
    weight = 5
    parent = "dropdown" 

[[menu.main]]
    name = "Australien"
    url = "/fallstudien/australien/"
    weight = 3
    parent = "dropdown" 

[[menu.main]]
    name = "Südamerika"
    url = "/fallstudien/suedamerika/"
    weight = 6
    parent = "dropdown"

	
[[menu.footer]]
    identifier = "Über Uns"
    pre = "<p>Über Uns</p>"
    url = "#"
    weight = 1

[[menu.footer]]
    identifier = "Projekte"
    pre = "<p>Projekte</p>"
    url = "#"
    weight = 2
	

[params]